### ISSUE TITLE
English Rule

### ISSUE THREAD

**Issue by anseljh** [kemitchell/goldplate#9]
Some California-specific aspects like [Civil Code section 1717](https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=1717.)

**Comment by kemitchell** [comment]
This are isn't particularly well known to me. Might you have a clause we could use as a starting point?

**Comment by kemitchell** [comment]
Oh, now I see. I didn't recognize the section reference.
